#!/usr/bin/env bash
# To print numbers 1 to 100 in list
# To print "Buzz" when the number is a multiple of 5
# To print "Fizz" when the number is a multiple of 3
# To print FizzBuzz when the number is multiple of 5
# Else print the list

for k in {1..100}
do
	if (( k % 3 == 0 && k % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( k % 3 == 0 ))
	then
		echo "Fizz"
	elif (( k % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$k"
	fi
done
