#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
# in the 4th iteration, display bad luck
# in the 8th iteration, display good luck
# then best school for others

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
