#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
# on the 4th iteration, displays bad luck from china
# on the 9th iteration, displays bad luck from japan
# on the 17th iteration, bad luck from italy

k=1

while [ $k -le 20 ]
do
	echo "$k"
	case $k in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( k++))
done
