#!/usr/bin/env bash
# This displays the time for 12 hours and 59 mins.
# Also displays hours from 0 to 12
# Then displays minutes from 1 to 59

hr=0

while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hr++ ))
done
